name: Rust Code Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate Cobertura XML Report
        run: cargo llvm-cov --all-features --cobertura --output-path cob.xml

      - name: Generate Detailed Coverage Report
        run: python3 scripts/render-coverage-rust.py cob.xml rust-coverage-report.md

      - name: Write to Job Summary
        run: cat rust-coverage-report.md >> $GITHUB_STEP_SUMMARY